steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$REPO_NAME:$SHORT_SHA', '.']

  # Verify the image was built and tagged correctly
  - name: 'gcr.io/cloud-builders/docker'
    args: ['images', 'us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$REPO_NAME:$SHORT_SHA']

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$REPO_NAME:$SHORT_SHA']

  # Deploy to Cloud Run with a real, random SECRET_KEY
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        # generate a real hex secret
        SECRET=$(openssl rand -hex 24)
        echo "▶ Using SECRET_KEY: $SECRET"

        # deploy, injecting the generated value
        gcloud run deploy "$REPO_NAME" \
          --image "us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$REPO_NAME:$SHORT_SHA" \
          --region us-central1 \
          --set-env-vars SECRET_KEY="$SECRET"


#  # Deploy the image to Cloud Run
#  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#    entrypoint: gcloud
#    args: [
#      'run',
#      'deploy',
#      '$REPO_NAME',
#      '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$REPO_NAME:$SHORT_SHA',
#      '--region', 'us-central1',
#      '--set-env-vars', 'SECRET_KEY=$(openssl rand -hex 24)'
#    ]

images:
  # Specify the Docker image to be pushed to Artifact Registry
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$REPO_NAME:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
